#:kivy 1.0.9
<Test>:
        canvas:
                Color:
                        rgba: 2, 1, 0, .5
                Rectangle:
                        pos: self.center_x, -100
                        size: 20, self.height
                Color:
                        rgba: 0, 1, 2, .6
                Rectangle:
                        pos: 0, self.height - 100
                        size: self.width, 20

        Label:

